import type { Metadata } from "next";  
import localFont from "next/font/local";  
import "./globals.css";  
import { ClerkProvider } from "@clerk/nextjs";  
import ConvexClerkProvider from "@/components/ui/providers/ConvexClerkProvider";

const geistSans = localFont({  
  src: "./fonts/GeistVF.woff",  
  variable: "--font-geist-sans",  
  weight: "100 900",  
});  
const geistMono = localFont({  
  src: "./fonts/GeistMonoVF.woff",  
  variable: "--font-geist-mono",  
  weight: "100 900",  
});  

export const metadata: Metadata = {  
  title: "Create Next App",  
  description: "Generated by create next app",  
};  

// Directly using the publishable key here  
//const PUBLISHABLE_KEY = "pk_test_dW5pcXVlLXBlZ2FzdXMtMzkuY2xlcmsuYWNjb3VudHMuZGV2JA"; // Replace this with your actual publishable key  

export default function RootLayout({  
  children,  
}: Readonly<{  
  children: React.ReactNode;  
}>) {  
  return (  
    <ConvexClerkProvider>  
      <html lang="en">  
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>  
          {children}  
        </body>  
      </html>  
    </ConvexClerkProvider>  
  );  
}  